<Project Sdk="Microsoft.NET.Sdk.razor">  

  <ItemGroup>
    <ProjectReference Include="..\HR.Core\HR.Core.csproj" />
    <ProjectReference Include="..\HR.Data\HR.Data.csproj" />
    <ProjectReference Include="..\HR.Utilities\HR.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Google.GenAI" Version="1.1.0" />
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.13" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="QuestPDF" Version="2022.12.5" />
    <PackageReference Include="Solutaris.InfoWARE.ProtectedBrowserStorage" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DinkToPdfLibs\wkhtmltoimage.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DinkToPdfLibs\wkhtmltopdf.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DinkToPdfLibs\wkhtmltox.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
